[package]
name = "blenvy_demo"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = { version = "0.15.3", features = ["dynamic_linking"] }
blenvy = { path = "../../crates/blenvy" }
rand = "0.9.0"
avian3d = "0.2.1"